10 rem invention 13 by j.s. bach
20 tempo 6
30 a$="v1o4t7u8x0 v2o4t7u8x0":rem v1=organ, v2=piano
40 do
50 play a$
60 read a$
70 loop until a$="end of music"
80 end
90 rem **** first measure
100 data v2o1ia v1o3ie v2o2qa v1o3sao4co3bem
110 data v2o2i#g v1o3sbo4do4ic v2o2saem
120 data v1o4ie v2o2sao3c v1o3i#g v2o2sbem
130 data v1o4ie v2o2sbo3dm
140 rem **** second measure
150 data v2o3ic v1o3sae v2o2ia v1o3sao4cm
160 data v2o2i#g v1o3sbe v2o2ie v1o3sbo4dm
170 data v1o4ic v2o2sae v1o3ia v2o2sao3cm
180 data v1o4qr v2o2sbebo3dm
190 rem **** third measure
200 data v2o3ic v1o4sre v2o2ia v1o4scem
210 data v2o3ic v1o3sao4c v2o2ia v1o2segm
220 data v1o3if v2o3sdo2a v1o3ia v2o2sfam
230 data v1o4id v2o2sdf v1o4if v2o1sao2cm
240 rem **** fourth measure
250 data v2o1ib v1o4sfd v2o2id v1o3sbo4dm
260 data v2o2ig v1o3sgb v2o2ib v1o3sdfm
270 data v1o3ie v2o2sge v1o3ig v2o2segm
280 data v1o4ic v2o2sce v1o4ie v2o1sgbm
290 rem **** fifth measure
300 data v2o1ia v1o4sec v2o2ic v1o3sao4cm
310 data v1o3if v2o2sdf v1o4id v2o1sbo2dm
320 data v2o1ig v1o3sdb v2o1ib v1o3sgbm
330 data v1o3ie v2o2sce v1o4ic v2o1sao2cm
340 rem **** sixth measure
350 data v2o1if v1o4sco3a v2o1id v1o3sfam
360 data v1o3id v2o1sgo2g v1o3ib v2o2sfgm
370 data v2o1ia v1o4sco3a v2o2i#f v1o4scem
380 data v2o1ib v1o4sdo3b v2o2i#g v1o4sdfm
390 rem **** seventh measure
400 data v2o2ic v1o4sec v2o2ia v1o4segm
410 data v2o2id v1o4sfe v2o2i$b v1o4sdcm
420 data v2o2i#g v1o3sbo4c v2o2if v1o4sdem
430 data v2o2id v1o4sfd v2o1ib v1o4s#gdm
440 rem **** eighth measure
450 data v2o2i#g v1o4sbd v2o2ia v1o4scam
460 data v2o2id v1o4sfd v2o2ie v1o3sbo4dm
470 data v2o2if v1o3s#gb v2o2i#d v1o4sco3am
480 data v2o2ie v1o3sea v2o2ie v1o3sb#gm
490 rem **** ninth measure
500 data v2o1ha v1o3saeceo2qam
510 rem **** end of music ****
520 data end of music
